---
- name: Create an EC2 key
  ec2_key:
    name: "Ansible"
    region: "{{ aws_region }}"
  register: ec2_key

- name: Save private key
  copy: 
    content: "{{ ec2_key }}"
    dest: "Ansible.pem"
    mode: 0600
  when: ec2_key.changed 

- name: Ec2 Provisioning
  ec2:
    region: "{{ aws_region }}"
    image: "{{ ami_id }}"
    instance_type: "{{ ec2_instances_type }}"
    count: "{{ count }}"
    instance_tags: "{{ instance_tags }}"
    key_name: test
    vpc_subnet_id: subnet-5a94353c
    group: launch-wizard-1
    wait: yes
  register: ec2_out

- debug: var=item
  with_items: "{{ ec2_out.instances }}"  

- name: Add the newly created EC2 instance(s) to host group
  lineinfile: dest={{ hostpath }}
              regexp={{ item.public_ip }} 
              insertafter="[webservers]" 
              line="{{ item.public_ip }} {{hoststring}}"
              state=present
  with_items: ec2_out.instances

- wait_for: path={{ hostpath }} search_regex={{hoststring}}

- name: Wait for SSH to come up
  wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
  with_items: "{{ ec2_out.instances }}" 
  
- name: Add IP to ec2_hosts group
  add_host: hostname={{ item.public_ip }} groups=ec2_hosts
  with_items: "{{ ec2_out.instances }}"
